name: keep_note
description: A new Flutter project.


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  sqflite:
  path:  

  cupertino_icons: ^1.0.2
  google_fonts: ^3.0.1
  flutter_slidable: ^2.0.0
  share_plus: ^4.0.10
  shared_preferences: ^2.0.15
  rename: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "^0.9.2"
  
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/icons/icon.png" 
  remove_alpha_ios: true 



  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/images/image1.png
    - assets/images/image2.png
    - assets/images/image3.png
    - assets/images/icons/splash/icon.png
    - assets/images/icons/splash/page1.png
    - assets/images/icons/splash/page2.png
    - assets/images/icons/splash/page3.png
    - assets/images/icons/trash.png
    - assets/images/icons/icon.png
    - assets/images/about_icon.png
    
    # - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
